apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: gitlabregistry
data:
  .dockerconfigjson: $IMAGEPULLSECRET
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backups-manager
imagePullSecrets:
  - name: gitlabregistry
